### ISSUE TITLE
plugin doesn't start

### ISSUE THREAD

**Issue by kimuss** [doubletwisted/AutoDraft#1]
hello boss, 
thank you very much for your eventplugin, I think  can help me a lot in the studio, but it does not start when a job finished, how can debug this? I can not understand why does not start when job is finished... I use houdini render job
thank you for your help

**Comment by doubletwisted** [comment]
Hello.
Did you enabled plugin in "configure events"?
If yes, please show me what is displayed in Deadline Monitor's console

**Comment by kimuss** [comment]
there we go
![immagine](https://github.com/user-attachments/assets/07207044-6229-4549-9358-aaf2aca9725d)
the job should be created on any job completed right? Can I start an AutoDraft job on a finished job?

**Comment by doubletwisted** [comment]
Yes, you can do that. Just requeue one task and then mark it completed.  Do
that and check if something changed in console. Now it look like it didn't
picked up any event plugins recently

**Comment by kimuss** [comment]
I tried to requeue just the last frame to start AutoDraft but anything appened....

![10](https://github.com/user-attachments/assets/9c4eb608-3cab-4561-82fa-5879d42b2780)
![11](https://github.com/user-attachments/assets/d68cfd29-12f7-4fda-a518-68e8cf4a4452)

maybe miss any submission param?

![immagine](https://github.com/user-attachments/assets/74ed7180-5a41-4f3b-869d-03971b7ce7dd)

**Comment by doubletwisted** [comment]
What software are you rendering from? Did you add it to plugin filters?

**Comment by kimuss** [comment]
this is the only filters

![immagine](https://github.com/user-attachments/assets/0d4d0aba-d5dc-4015-aa94-74431987d24b)

we render with houdini/solaris/arnold, a official houdini submission plugin on deadline

**Comment by doubletwisted** [comment]
Please give me last logs of the worker that just completed the job and
job's logs. I will try to figure this out.

pt., 22 lis 2024 o 21:59 kimuss ***@***.***> napisał(a):

**Comment by kimuss** [comment]
Hello, this is the worker logs
![12](https://github.com/user-attachments/assets/6f807e3b-c2d0-4c42-be06-dd3fb438e143)

job's log is there?
I'm not sure:
If you mean job report, its exactly like worker job
![13](https://github.com/user-attachments/assets/6893d362-31ea-41bc-9297-05177d2dcb9f)

**Comment by doubletwisted** [comment]
Please try it now, I've updated the code

**Comment by kimuss** [comment]
Hello,
thank you very much, I have to take only AutoDraft.py?
if I take only that:
`Event plugin 'AutoDraft' could not be loaded from the repository because: Error executing event plugin script "\\192.168.2.77\DeadlineRepository\custom\events\AutoDraft\AutoDraft.py": invalid character 'ú' (U+00B7) (none, line 100) (Deadline.Events.DeadlineEventPluginException)`

**Comment by doubletwisted** [comment]
This is very weird, because there is  not    "ú" anywhere in the code. I
think there can be something wrong with your deadline installation, your
database or something like this. I've tested this on multiple PC, and it
works fine.

**Comment by doubletwisted** [comment]
Or as a last try do this:
add this line on very top of the AutoDraft.py
:
# -*- coding: utf-8 -*-

save it and try to reload plugin

**Comment by kimuss** [comment]
sorry my bad, I pasted a wrong file.
I'll try soon
thank you for your support

**Comment by kimuss** [comment]
Hey man, sorry for the late reply, with the updated file, I have the same problem, no error on console, autodraft and autodraft copy in goblal enabled...
I don't know how to fix that, can you share a video or a screen about how that script autocreate the job? can you try with a houdini job? I tried also to update deadline to 10.4.0.10... 
thank you for your time

**Comment by kimuss** [comment]
a little news,
the event plugin work perfectly with a maya job, so the problem seems to be the houdini submitter... 
Have you a chance to try your script with a houdini job?

**Comment by doubletwisted** [comment]
That's valuable info!
I only use it with Houdini, with Redshift, without Solaris. I will take a
look what it can be.

**Comment by kimuss** [comment]
oh ok, we triyng to use it in Solaris Arnold, it seems ROP node does not recognize the output path file (it is blank..  image attached)
![immagine](https://github.com/user-attachments/assets/4c0313ff-07f6-4d82-a0f8-1a6333e7d24b)

**Comment by doubletwisted** [comment]
I see that renders from Solaris Karma don't populate the Output filename
either. If you need help with this, please try Deadline forums. The
submitter needs to be edited.

**Comment by kimuss** [comment]
do you think that is the problem? if the submitter populate the output filename, the autodraft works?

**Comment by doubletwisted** [comment]
Yes, that's probably it.

**Comment by kimuss** [comment]
I'm no sure the problem is output path, because if I open a py, I find    
```
if len(outputFilenames) == 0:
            raise Exception("ERROR: Could not find a full output path in Job properties; No Draft job will be created.")
```

but this error is not printed on log job report, there is only:
```
 AutoDraft: Starting OnJobFinished handler
 AutoDraft: Checking filters - Job Group: none, Job Name: 810_010_preview_v001 - /stage/810_010_PREVIEW, Plugin: Houdini
```

**Comment by doubletwisted** [comment]
For next project i will use Solaris and try to figure this out. I will let
you know.

**Comment by doubletwisted** [comment]
I can confirm that this was the problem. Maybe I Will update the code, so
that the correct error is raised.
Try this submitter:
https://forums.thinkboxsoftware.com/t/official-houdini-solaris-husk-submitter/30214/127

**Comment by doubletwisted** [comment]
Or maybe this one will be better:
https://forums.thinkboxsoftware.com/t/official-houdini-solaris-husk-submitter/30214/100

**Comment by kimuss** [comment]
Thank you, but I don't know how can I use the .targz file
your second link is older than the first, Its better the older?

**Comment by doubletwisted** [comment]
Both are good, but I used this one:

**Comment by kimuss** [comment]
mmmm I don't know how to use that plugin, can you tell me how can load it on houdini?
i tried to paste HoudiniVFX in repository->custom->submission folder, I see the plugin option on monitor, but how can I submit a job?

**Comment by doubletwisted** [comment]
1. Copy all your Houdini files from DeadlineRepository10\submission and
DeadlineRepository10\plugins  to  DeadlineRepository10/custom folders.
2. Copy files from HoudiniSolarisSubmitter.zip  to
DeadlineRepository10\custom\submission\Houdini and replace the files
It should work

**Comment by kimuss** [comment]
> all your Houdini files

You mean .hip work file?
